/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateVisualSummaryRouteImport } from './routes/api/generate-visual-summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVisualSummaryRoute =
  ApiGenerateVisualSummaryRouteImport.update({
    id: '/api/generate-visual-summary',
    path: '/api/generate-visual-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-visual-summary': typeof ApiGenerateVisualSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-visual-summary': typeof ApiGenerateVisualSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-visual-summary': typeof ApiGenerateVisualSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate-visual-summary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-visual-summary'
  id: '__root__' | '/' | '/api/generate-visual-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateVisualSummaryRoute: typeof ApiGenerateVisualSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-visual-summary': {
      id: '/api/generate-visual-summary'
      path: '/api/generate-visual-summary'
      fullPath: '/api/generate-visual-summary'
      preLoaderRoute: typeof ApiGenerateVisualSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateVisualSummaryRoute: ApiGenerateVisualSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
